name: selenoid
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-selenoid:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      SELENOIDTEST: 1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: docker-compose -f docker-compose.test.yml run bot python -m pytest tests/bot/test_bot_selenoid.py -vv