name: Test-selenoid
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-selenoid:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      LOCALTEST: 1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: LOCALTEST=1 docker-compose -f docker-compose.test.yml run bot python -m pytest tests/bot/test_bot.py::test_selenoid_text -vv